### ISSUE TITLE
Search bar not working

### ISSUE THREAD

**Issue by alchemiker** [sbsev/svelte-site#12]
When searching a page via the search tool on the website and choosing it from the dropdown menu, an error occurs.

Steps to reproduce:

1. Type "Satzung" in the search field. (Or something else.)
2. Click on the first suggestion.

You will be redirected to `https://studenten-bilden-schueler.de/<em>satzung</em>`. The page appears blank apart from header and footer. If you then click at any other of the section links in the header, like "Standorte", the URL in the browser will change to the appropriate site, but the content of the window remains the same until you hit "refresh" in the browser.

If I get a hint where to look I can try to tackle this problem by myself... (*_still confused from all this code_)

**Comment by janosh** [comment]
@alchemiker Thanks for letting us know! I just fixed this in 602b859.

Sadly, the fix won't appear on our live website immediately which is pinned to an older version currently. The reason for that is the site underwent a major overhaul that is almost but not quite done yet. The signup forms don't do proper input validation yet. As soon as we have that (hopefully next week), we'll release this fix to our production site.
