### ISSUE TITLE
Wrong town and line-breaking issue

### ISSUE THREAD

**Issue by alchemiker** [sbsev/svelte-site#3]
Hello everybody, I found some issues at your page. They are small and I don't want to flood the "Issues" section, so I put them into this one issue.

1. at the page https://studenten-bilden-schueler.de/standorte/hamburg the first line of the text says: „Der Standort Oldenburg befindet sich gerade in Gründung.“ It should rather say „Der Standort _Hamburg_ befindet sich gerade in Gründung.“
2. In the school kids application form at https://studenten-bilden-schueler.de/anmeldung?type=Sch%C3%BCler&chapter=Hamburg there is at the screen size of my phone several time a wrong hypothenation of the word „Bestätigungsemail“ displayed. It is seen as „Bestätigungse-mail“, but should be „Bestätigungs-email“ instead. I think a _shy hyphen_ should suffice to fix this minimal issue.

If you like, I could try to fix it on my own and submit a pull request containing the changes.
EDIT: I take my offering back 😅 the sourcecode looks completely different to that little HTML I know...

**Comment by janosh** [comment]
Thanks for letting us know! As you already seem to have noticed, our content isn't actually part of this repo but lives in Contentful. As a result, this is not something you can fix yourself but I went ahead and published fixes. Please let us know if you find further typos/bugs/errors! 👍
