### ISSUE TITLE
Consider using endpoint post handlers for sending signup data to Airtable

### ISSUE THREAD

**Issue by janosh** [sbsev/svelte-site#36]
Not sure if this is really better but we may want to send signup form data to Airtable via a `post()` handler instead of importing the submit function manually. Not sure which is really better, our current approach probably has better type checking but is more verbose.

Docs on post handlers:
https://kit.svelte.dev/docs/routing#endpoints-post-put-patch-delete

Code to change:
https://github.com/sbsev/svelte-site/blob/ab1855a9caf2a3c763a5782f4d4a7ccab3e91bdf/src/routes/signup-student.svelte#L49-L62

**Comment by dominikgeissler** [comment]
See #51
