### ISSUE TITLE
Submit Werbemaßnahme from pupils correctly

### ISSUE THREAD

**Issue by kleinicke** [sbsev/svelte-site#38]
In recent submits, only the first letter of the Werbemaßnahme from pupils is submitted to Airtable.

**Comment by janosh** [comment]
That's from a recent breaking change in svelte-multiselect v5. Easy to fix.

**Comment by kleinicke** [comment]
Ok, a different symptom might be type of signup is only stored as s or p instead of pupil or student in plausible.
