### ISSUE TITLE
Kontaktpersonen for Students

### ISSUE THREAD

**Issue by kleinicke** [sbsev/svelte-site#44]
When submitting the students entry, sometimes the error comes up, that there is no "Kontaktpersonen" in the Airtable entry. 
The Problem is, that the Kontaktpersonen field of the pupil base might be filled beforehand, so there is a value for that keyword.

**Comment by dominikgeissler** [comment]
Maybe adjust the corresponding message in airtable.ts?

**Comment by janosh** [comment]
> The Problem is, that the Kontaktpersonen field of the pupil base might be filled beforehand, so there is a value for that keyword.

@kleinicke That hypothesis can't be it. Looking at the code, the form fields to send to Airtable are specified explicitly as `fieldIds`. They are not set as whichever fields are currently populated in `localStorage`.

https://github.com/sbsev/svelte-site/blob/46eefa3c3eccd67f7fbd3a722829dd5a27dc3778/src/routes/signup-student.svelte#L54-L56

Instead the problem appears to be that we have a legacy hardcoded insertion of 'Kontaktpersonen' into `chapterFields` in `prepare_signup_data_for_airtable()`. Pretty sure that was left there inadvertently.

https://github.com/sbsev/svelte-site/blob/46eefa3c3eccd67f7fbd3a722829dd5a27dc3778/src/utils/airtable.ts#L100-L102

**Comment by kleinicke** [comment]
Ok, so the `Kontaktpersonen: data.nameContact?.value` should be moved 15 lines up into pupilFields.
But most of the time this works, and I think it's because when data.nameContact?.value is undefined, the Keyword should be ignored by airtable (and is ignored most of the times by airtable).

**Comment by janosh** [comment]
> Ok, so the Kontaktpersonen: data.nameContact?.value should be moved 15 lines up into pupilFields.

Go ahead.

**Comment by dominikgeissler** [comment]
With the Azure Function as Middleware we will add server-side validation regarding the object structure. Therefore, this issue or any related issues should be fixed afterwards.

**Comment by dominikgeissler** [comment]
See #51
