### ISSUE TITLE
Code fragment in registration form

### ISSUE THREAD

**Issue by alchemiker** [sbsev/svelte-site#8]
Hello, thank you very much for improving the registration form recently! It looks nice!
But I found a bug on the students registration form, right after „Erklärung über Vorstrafen“.
 I marked the code snippet showing in the screenshot below.
![Screenshot_20210425-113806](https://user-images.githubusercontent.com/63516327/115988727-521c8400-a5bb-11eb-9bd1-519c6d48d3c9.png)

**Comment by janosh** [comment]
Thanks for the kind words and great catch! Should be fixed in a minute!
